const { Prisma } = require("@prisma/client");

const charities = [
  {
    name: "RSPCA",
    email: "",
    social: false,
    education: false,
    conservation: false,
    environmental: false,
    cultural: false,
    training: false,
    animals: false,
    science: false,
    bio: "",
    email_address: "",
    website: "",
    tiktok: "",
    instagram: "",
    snapchat: "",
  },
  {
    name: "NSPCC",
    email: "",
    social: false,
    education: false,
    conservation: false,
    environmental: false,
    cultural: false,
    training: false,
    animals: false,
    science: false,
    bio: "",
    email_address: "",
    website: "",
    tiktok: "",
    instagram: "",
    snapchat: "",
  },
  {
    name: "WWF",
    email: "",
    social: false,
    education: false,
    conservation: false,
    environmental: false,
    cultural: false,
    training: false,
    animals: false,
    science: false,
    bio: "",
    email_address: "",
    website: "",
    tiktok: "",
    instagram: "",
    snapchat: "",
  },
  {
    name: "THE ARTS COUNCIL OF ENGLAND",
    email: "",
    social: false,
    education: false,
    conservation: false,
    environmental: false,
    cultural: false,
    training: false,
    animals: false,
    science: false,
    bio: "",
    email_address: "",
    website: "",
    tiktok: "",
    instagram: "",
    snapchat: "",
  },
];

const businesses = [];

const users = [
  {
    username: "ioetbc",
    email: "ioetbc@gmail.com",
  },
];

module.exports = {
  charities,
  businesses,
  users,
};
